site_name: Openveo Core
repo_url: https://github.com/veo-labs/openveo-core
theme: readthedocs
site_dir: site/version
markdown_extensions:
  - fenced_code
  - tables
nav:
- 'INTRODUCTION': 'index.md'
- 'USERS':
  - 'Prerequisites': 'prerequisites.md'
  - 'Getting started': 'getting-started.md'
  - 'Web Service': 'web-service.md'
  - 'Advanced configuration': 'advanced-configuration.md'
  - 'Plugins': 'plugins.md'
  - 'Scalability': 'scalability.md'
  - 'Production': 'production.md'
- 'DEVELOPERS':
  - 'The basics': 'developers/basics.md'
  - 'Prerequisites': 'developers/prerequisites.md'
  - 'Installation': 'developers/installation.md'
  - 'Back end AngularJS': 'developers/back-end.md'
  - 'Template engine': 'developers/template-engine.md'
  - 'Plugins': 'developers/plugins.md'
  - 'API': 'developers/api.md'
  - 'Logger': 'developers/logger.md'
  - 'I18N and I10N': 'developers/i18n.md'
  - 'Compilation': 'developers/compilation.md'
  - 'Coding standards': 'developers/coding-standards.md'
  - 'Unit tests': 'developers/unit-tests.md'
  - 'End to end tests': 'developers/end-to-end-tests.md'
